apiVersion: v2
name: conduix
description: Conduix - 데이터 파이프라인 관리 플랫폼
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - data-pipeline
  - conduix
  - etl
  - streaming

home: https://github.com/conduix
sources:
  - https://github.com/conduix

maintainers:
  - name: Conduix Team
    email: team@example.com

dependencies:
  - name: mysql
    version: "9.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled
  - name: redis
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
