---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "conduix.fullname" . }}-control-plane
  labels:
    {{- include "conduix.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: {{ .Values.controlPlane.service.type }}
  ports:
    - port: {{ .Values.controlPlane.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "conduix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "conduix.fullname" . }}-agent
  labels:
    {{- include "conduix.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  type: {{ .Values.agent.service.type }}
  ports:
    - port: {{ .Values.agent.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "conduix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "conduix.fullname" . }}-web-ui
  labels:
    {{- include "conduix.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
spec:
  type: {{ .Values.webUI.service.type }}
  ports:
    - port: {{ .Values.webUI.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "conduix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
